import type {
  Direction, HtfBias, Instrument, Outcome, PremiumDiscount, Reason, Session, SetupType, TargetType,
} from './domain';
import type { GradeLetter } from './grade';

/** A trade as the app uses it: real booleans, derived grade attached. */
export interface Trade {
  id: string;
  date: string;
  instrument: Instrument;
  direction: Direction;
  session: Session;
  macro_time: boolean;
  macro_time_auto: boolean;
  reason: Reason;
  setup_type: SetupType;
  htf_bias: HtfBias;
  sweep_before_entry: boolean;
  singular_gap: boolean;
  target_unswept: boolean;
  displacement: boolean;
  mss_confirmed: boolean;
  volume_imbalance: boolean;
  consequent_encroachment: boolean;
  equal_highs_lows: boolean;
  retest_entry: boolean;
  news_window: boolean;
  premium_discount: PremiumDiscount;
  target_type: TargetType;
  smt: boolean;
  candle_strength: number;
  inversion_speed: number;
  risk_reward: number;
  /** Generated by SQLite from the three rubric scores. Never written. */
  grade_total: number;
  grade_letter: GradeLetter;
  contracts: number | null;
  risk_dollars: number | null;
  stop_points: number | null;
  outcome: Outcome;
  r_multiple: number | null;
  explanation: string;
  lesson: string | null;
  screenshot_path: string;
  position_x: number | null;
  position_y: number | null;
  created_at: string;
  updated_at: string;
}

/** What the capture form sends. `id` and the generated columns are not yours to set. */
export type TradeInput = Omit<
  Trade,
  'id' | 'grade_total' | 'grade_letter' | 'created_at' | 'updated_at' | 'position_x' | 'position_y'
>;

/** The quick-settle path: outcome and R, without reopening the whole form. */
export interface SettleInput {
  outcome: Outcome;
  r_multiple: number | null;
}

export interface TradeFilters {
  from?: string;
  to?: string;
  outcomes?: Outcome[];
  reasons?: Reason[];
  sessions?: Session[];
  minGrade?: number;
  maxGrade?: number;
}

export const MIN_EXPLANATION = 80;
